### PR TITLE
FIX: Add way to change predicate and sorters for CoreDataSource

### PR DESCRIPTION
**Pull request by lj-dickey**
Add a way to change the predicate associated with a CoreData source
Add a way to change sorters as well
Added tests

### CODE REVIEW

**Comment by kreeger** [comment]
[Based on this comment](https://stackoverflow.com/a/34713754/194869), the delegate will not get notified when the results change as a consequence of the predicate changing. It might be worthwhile to add a new closure property to the `CoreDataSource` to let its listener know that it needs to refresh its table view or collection view entirely.

**Comment by lj-dickey** [comment]
Yes, the delegate doesn't get notified (I was kind of hoping that it would).  Instead, I just do a `reloadData` on the collection view since I'm not going to get the inserts/deletes.  I could add a new closure method, or could just document the fact that you'll need to refetch the data.  I added this at the `CoreDataSource` level instead of the `DataSource` level because it's very CoreData specific, and I worry a bit about adding too much extra stuff to the class, but I'm open to it if you'd like me to support it...

**Comment by lj-dickey** [comment]
Requested changes plus improved comments pushed, also rebased so that I pick up the new pod spec version.

**Comment by kreeger** [comment]
That's a great point. I'd note it in the docstring comments of the properties you've added!

**Comment by lj-dickey** [comment]
I think I did update the comment?

**Pull request merged**
