### PR TITLE
FIX: Add support for a combine publisher for CoreDataSource

### PR DESCRIPTION
**Pull request by lj-dickey**
Add a simple `CurrentValueSubject` publisher to a `CoreDataSource`.  It should get updated whenver the predicate changes, or other changes to the data source.
Roll to version 1.0.0 because this is a breaking change for MacOS because it requires a newer OS version.

### CODE REVIEW

**Review by mblackmon — CHANGES_REQUESTED** [review]
Changes look good!  I'm looking forward to using this.  However, the build is failing.  Would you please check it?

**Comment by mblackmon** [comment]
Looks like tvOS version needs to bump too.

**Comment by lj-dickey** [comment]
Yup, that should be fixed now too.

**Review by mblackmon — APPROVED** [review]
Thanks for the updates!

**Pull request merged**
