### PR TITLE
GUAC-5584 Update project settings and fix language warnings

### PR DESCRIPTION
**Pull request by lj-dickey**
There were a few protocols from system libraries that we extend, so annotate them to make the compiler happy.

Also update to recommended project settings as of XCode 16.

### CODE REVIEW

**Comment by lj-dickey** [comment]
Right now this is still trying to use Bitrise to build -- probably needs to be moved over to Xcode Cloud. But, it's fast and easy to run tests locally (they only take a few seconds).

**Review by theconstellationiris — COMMENTED** [review]
First pass looks fine to me! Gonna run tests locally now, and also point to this branch in SPM to make sure things are still golden, but I'm not expecting issues.

**Review by mblackmon — APPROVED** [review]
👍

**Comment by lj-dickey** [comment]
Thanks for the review! I'll tag it now but wait to update puffin with the new version until after 10.7 is cut.

**Pull request merged**
