### PR TITLE
FIX: Fix warnings, linter, test issues

### PR DESCRIPTION
**Pull request by kreeger**
This PR fixes some issues that popped up lately during Xcode builds, including linter warning, test scheme problems with Bitrise, and some code that didn't actually compile under macOS (in our tests).

### CODE REVIEW

**Comment by mblackmon** [comment]
Here's what I ran across while putting this through the paces:
- `CoreDataAccessStoreTypeTests:testStoreTypeSQL` fails when testing iOS
- Two of the `tvOS` targets would not build, the coredata one and the unit test one.
- The example only runs on iOS, but I think that's intentional, so it's not really an issue.

The code changes look good, and an overall improvement. I'm fine with spinning off the points above into another issue and letting this go through.

**Comment by kreeger** [comment]
- Can you give me more info on the iOS failure? That shouldn't be happening and it's not happening to me
- Lemme check this, I actually haven't run the tvOS tests in a while
- Yeah the example only runs iOS tests

**Comment by kreeger** [comment]
Oh weird, the iOS test fails now!

**Comment by mblackmon** [comment]
Ah, I had the iOS test set to `My Mac`.  Once I picked an actual simulator, no problems.  My bad.

**Comment by kreeger** [comment]
Oh wait, are you running the `Tests-iOS` bundle tests against `My Mac`, or an iOS device?

**Comment by kreeger** [comment]
Haha jinx! Lemme check out the tvOS issues.

**Comment by kreeger** [comment]
Hooray! Tests pass again. I made sure the Bitrise workflow tests all three platforms now.

**Review by mblackmon — APPROVED** [review]
Looks good!

**Pull request merged**
